### ISSUE TITLE
Cannot find train_ret_encdec_clip_anet.sh

### ISSUE THREAD

**Issue by BUAAPY** [ailab-kyunghee/CM2_DVC#1]
Excellent work! 
But I cannot find train_ret_encdec_clip_anet.sh.
When I try to run train_anet.sh, I got an error: 
 ModuleNotFoundError: No module named 'densevid_eval3.SODA'

**Comment by Geppa** [comment]
Thanks for showing interest in my research!

1. Renamed the shell script to match the README.
2. Fixed the issue with the missing Metric folders and updated it.

Thanks for your attention and feedback!
