### ISSUE TITLE
How to get YouCook2 Videos?

### ISSUE THREAD

**Issue by JayParanjape** [ailab-kyunghee/CM2_DVC#3]
Hi, How do you get the videos for the youcook2 datasets, since they only provide annotations? Would I need to download each video from youtube? Or do you provide embeddings for the videos?

Thanks

**Comment by Geppa** [comment]
Hi, we also don't have the raw videos due to expired videos of youtube. We got the embeddings(CLIP features 1fps) from [Vid2Seq](https://github.com/google-research/scenic/tree/main/scenic/projects/vid2seq) Authors. 

Thanks.

**Comment by JayParanjape** [comment]
I see. Thanks
