### ISSUE TITLE
Unable to retrain on the ActivityNet dataset?

### ISSUE THREAD

**Issue by ydwl-lynn** [ailab-kyunghee/CM2_DVC#4]
When retraining ActivityNet using the CM2 model, I got an error and could not generate info.json, model-best.pth and model-last.pth files.

**Comment by Geppa** [comment]
Hi, i recommend you to make sure your folder path for saving models.

**Comment by Chris-MMM** [comment]
there's a path error in anet_clip_cm2.yml
`gt_file_for_eval: ['data/anet/captiondata/val_1.json', **'ata/anet/captiondata/val_2.json'**]`
'd' is missing
